module.exports = {
  name: "configurartextosticket",
  type: "interaction",
  prototype: "modal",
  code: `
$interactionupdate[{newEmbed: {title:Painel de Configuração de Tickets}{description:Selecione uma opção abaixo para configurar o painel de tickets.}{field:$customemoji[staff] | Cargo Atendente:$if[$roleexists[$getGuildVar[cargo_ticket]]==true;<@&$getGuildVar[cargo_ticket]>;Cargo não Configurado/Existente]}{field:$customemoji[registros] | Canal de Registros:$if[$guildchannelexists[$guildid;$getGuildVar[registros_ticket]]==true;<#$getGuildVar[registros_ticket]>;Canal não Configurado/Existente]}{field:$customemoji[star] | Canal de Feedbacks:$if[$guildchannelexists[$guildid;$getGuildVar[feedbacks_ticket]]==true;<#$getGuildVar[feedbacks_ticket]>;Canal não Configurado/Existente]}{field:$customemoji[color] | Cor dos Paineis:$getGuildVar[color_ticket]}{color:$getGuildVar[color_ticket]}{thumbnail:$guildicon}{author:$guildname | Atendimentos}{footer:$guildname | Todos os Direitos Reservados}}{actionRow:{selectMenu:ticket_configurar:Selecione a Opção que Deseja Configurar.:1:1:false:{stringInput:Cargo Atendente:cargo_ticket:Cargo que poderá ver os Tickets.::$customemoji[staff]}{stringInput:Canal de Registros:registros_ticket:Canal onde será enviado os Registros de Tickets.::$customemoji[registros]}{stringInput:Canal de Feedbacks:feedbacks_ticket:Canal onde será enviado os Feedbacks dos Tickets.::$customemoji[star]}}} {actionRow: {button:Configurar Textos:primary:configurartextos_ticket::🖌}{button:Variáveis:success:variaveistextos_tickets::🗝}{button:Gerenciar Opções:secondary:gerenciaropcoes_ticket::⚙️}};;true]
$setGuildVar[descricao_ticket;$if[textinputvalue[descricaopainel]==RESETAR;$getChannelVar[descricao_ticket];$replaceText[$textinputvalue[descricaopainel];RESETAR;$getChannelVar[descricao_ticket]]]]
$setGuildVar[titulo_ticket;$if[textinputvalue[titulopainel]==RESETAR;$getChannelVar[titulo_ticket];$replaceText[$textinputvalue[titulopainel];RESETAR;$getChannelVar[titulo_ticket]]]]
$setGuildVar[descricao_b_ticket;$if[textinputvalue[descricaobbpainel]==RESETAR;$getChannelVar[descricao_b_ticket];$replaceText[$textinputvalue[descricaobbpainel];RESETAR;$getChannelVar[descricao_b_ticket]]]]
$setGuildVar[titulo_b_ticket;$if[textinputvalue[titulobbpainel]==RESETAR;$getChannelVar[titulo_b_ticket];$replaceText[$textinputvalue[titulobbpainel];RESETAR;$getChannelVar[titulo_b_ticket]]]]
$if[$isValidImageLink[$textinputvalue[bannerpainel]]==true;$setGuildVar[banner_ticket;$if[textinputvalue[bannerpainel]==RESETAR;$getChannelVar[banner_ticket];$replaceText[$textinputvalue[bannerpainel];RESETAR;$getChannelVar[banner_ticket]]]]]
     $suppresserrors
  `
}